@if "%uname%"=="" goto error1
@if "%passwd%"=="" goto error1
@if "%server%"=="" goto error1

@if "%~1"=="" @goto error2
@set productid=%~1
@echo. Registering product %productid%

@rem we create an instance of a Thingtemplate here by calling thingworx using a helper service calle shareHelper
@rem as an example, it takes as a parameter the productid we are setting 
@rem the name of the Thing (the share) is generated by thingworx and passed back to us, the caller
@rem we map this to the instanceId

@rem create thing from the template service
@curl -u %uname%:%passwd% -H "X-Requested-With: XMLHttpRequest" -H "accept:application/json" -H "content-type: application/json" ^
-d "{ \"productid\":\"%productid%\" }" ^
-k %server%/Thingworx/Things/designShareHelper/Services/createNewShare %verbose% --output __p7
@rem test the results - did we create the thing?
@set result=
@for /f "tokens=1,2 delims=[] " %%a in (__p7) do @echo %%~b > __p8
@for /f "tokens=1,2 delims=,:[{}] " %%a in (__p8) do @set %%~a=%%~b
@if /I "%result%" EQU "" goto thingfail
@set thingname=%result%
@echo Created %thingname%

:qr
@rem using QR code
@curl -k "https://quickchart.io/chart?cht=qr&chs=300x300&chl=https://view.vuforia.com/command/view-experience?url=https%%253A%%252F%%252Fqatwx93.studio-trial.thingworx.io%%252FExperienceService%%252Fcontent%%252Fprojects%%252Fsharing%%2520assets%%2520101%%252Findex.html%%253FexpId%%253D2%%2526productid%%253D%productid%" --output qr-%productid%.png
@echo. created QR code for productid %productid% - see qr-%productid%.png
@echo {"shareId":"qr-%productid%.png"} > __p3
@goto done
:thingfail
@echo. Failed to create Thing
:error2
@echo usage : create_and _share ^<productID^>
@echo:
@echo    e.g. create_and _share quad101  
@set ERRORLEVEL=1
:done
